# Generated by Django 3.2.25 on 2024-07-23 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='pnumber',
            new_name='sub',
        ),
    ]
