# Generated by Django 3.2.25 on 2024-07-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
