# Generated by Django 3.2.25 on 2024-07-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20240730_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
