# Generated by Django 3.2.25 on 2024-08-01 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
