# Generated by Django 3.2.25 on 2024-08-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20240806_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
