# Generated by Django 3.2.25 on 2024-08-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20240812_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dell',
            field=models.SmallIntegerField(default=0),
        ),
    ]
