# Generated by Django 3.2.25 on 2024-08-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_customer_orderplaced'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
