# Generated by Django 3.2.25 on 2024-08-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_delete_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Himachal', 'Himachal'), ('Chandigarh', 'Chandigarh'), ('Punjab', 'Punjab'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Rajasthan', 'Rajasthan'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Gujarat', 'Gujarat'), ('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana'), ('Tamil Nadu', 'Tamil Nadu'), ('Kerala', 'Kerala'), ('Odisha', 'Odisha'), ('West Bengal', 'West Bengal'), ('Bihar', 'Bihar'), ('Jharkhand', 'Jharkhand'), ('Assam', 'Assam'), ('Meghalaya', 'Meghalaya'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Sikkim', 'Sikkim'), ('Nagaland', 'Nagaland'), ('Mizoram', 'Mizoram'), ('Manipur', 'Manipur'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand')], max_length=50),
        ),
    ]
