# Generated by Django 3.2.25 on 2024-08-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percentage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
