# Generated by Django 3.2.25 on 2024-08-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_product_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='product/'),
        ),
    ]
